const fs=require('fs'),path=require('path');
const root=__dirname, repo=path.resolve(root,'../..');
const locales=['ja','en','zh'];
const themes=['cinematic','editorial','observatory','japanese','agri','human','midnight','modular','kinetic','constellation'];
const labels={ja:{about:'会社概要',news:'ニュース',ann:'公告',partners:'取引先',contact:'お問い合わせ',security:'情報セキュリティ基本方針',back:'一覧へ戻る',more:'詳しく見る',all:'すべて見る',home:'ホーム',lang:'言語',proposal:'デザイン案一覧'},en:{about:'About',news:'News',ann:'Announcements',partners:'Partners',contact:'Contact',security:'Information Security Policy',back:'Back to list',more:'Read more',all:'View all',home:'Home',lang:'Language',proposal:'All concepts'},zh:{about:'公司简介',news:'新闻',ann:'公告',partners:'合作伙伴',contact:'联系我们',security:'信息安全基本方针',back:'返回列表',more:'查看详情',all:'查看全部',home:'首页',lang:'语言',proposal:'所有设计方案'}};
const content=(loc,name)=>JSON.parse(fs.readFileSync(path.join(repo,'content',loc==='ja'?'':loc,name+'.json'),'utf8'));
const trans=loc=>JSON.parse(fs.readFileSync(path.join(repo,'src/locales',loc+'.json'),'utf8'));
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const paras=s=>String(s??'').split(/\n+/).map(x=>`<p>${esc(x)}</p>`).join('');
const svg=d=>`<svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="${d}"/></svg>`;
const icons=[svg('M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z'),svg('M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z'),svg('M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4'),svg('M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0'),svg('M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z')];
function target(loc,page){return page==='home'?`site/${loc}/index.html`:`site/${loc}/${page}/index.html`}
function rel(from,to){return path.relative(path.dirname(from),to).replaceAll('\\','/')||'./index.html'}
function shell(ctx,title,body){let {loc,file,theme,n}=ctx,L=labels[loc]; let nav=[['home',L.home],['about',L.about],['news',L.news],['announcements',L.ann],['partners',L.partners],['contact',L.contact]];return `<!doctype html><html lang="${loc}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | bestIEs</title><link rel="stylesheet" href="${rel(file,'assets/site.css')}"></head><body class="${theme}" style="--hero:url('${rel(file,'assets/hero.webp')}')"><a class="skip" href="#main">Skip to content</a><aside class="proposalbar"><a href="${rel(file,'../../index.html')}">← ${L.proposal}</a><span>CONCEPT ${n}</span></aside><header><div class="header-inner"><a class="brand" href="${rel(file,target(loc,'home'))}">best<span>IE</span>s</a><button class="menu" type="button" aria-expanded="false" aria-label="Menu"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><nav>${nav.map(([p,x])=>`<a href="${rel(file,target(loc,p))}">${x}</a>`).join('')}</nav><div class="langs">${locales.map(x=>`<a lang="${x}" href="${rel(file,file.replace(/^site\/(ja|en|zh)/,`site/${x}`))}">${x.toUpperCase()}</a>`).join(' ')}</div></div></header><main id="main">${body}</main><footer><strong>株式会社bestIEs</strong><nav>${nav.map(([p,x])=>`<a href="${rel(file,target(loc,p))}">${x}</a>`).join('')}<a href="${rel(file,target(loc,'security-policy'))}">${L.security}</a></nav><small>© bestIEs Inc. All rights reserved.</small></footer><script src="${rel(file,'assets/site.js')}"></script></body></html>`}
function cards(arr,fn){return `<div class="cards">${arr.map(fn).join('')}</div>`}
function build(n,loc,page,slug){let theme=themes[n-1],base=`concepts/${String(n).padStart(2,'0')}`,file=`site/${loc}/${page==='home'?'':page+'/'}index.html`,ctx={n:String(n).padStart(2,'0'),loc,file,theme};let t=trans(loc),news=content(loc,'news').sort((a,b)=>b.date.localeCompare(a.date)),company=content(loc,'company'),partners=content(loc,'partners'),ann=content(loc,'announcements'),pol=content(loc,'security-policy'),L=labels[loc],body,title;
 if(page==='home'){let services=['consulting','iot','app','infra','haccp'];body=`<section class="hero"><div class="reveal"><p class="eyebrow">bestIEs / Hiroshima</p><h1>${esc(t.hero.title1)}<br>${esc(t.hero.title2)}</h1>${paras(t.hero.description)}<div class="hero-actions"><a class="button hero-contact" href="${rel(file,target(loc,'contact'))}">${esc(t.hero.contactButton)}</a><a class="button hero-about" href="${rel(file,target(loc,'about'))}">${esc(t.hero.aboutButton)}</a></div></div></section><section><h2>${esc(t.services.title)}</h2><p class="lead">${esc(t.services.subtitle)}</p>${cards(services,(x,i)=>`<article class="reveal">${icons[i]}<h3>${esc(t.services[x].title)}</h3><p>${esc(t.services[x].description)}</p></article>`)}</section><section class="scene"><div class="reveal"><h2>${esc(t.whyUs.title)}</h2>${cards(['fieldFirst','totalSupport','expertise'],x=>`<article><h3>${esc(t.whyUs[x].title)}</h3><p>${esc(t.whyUs[x].description)}</p></article>`)}</div></section><section><h2>${esc(t.targetMessages.title)}</h2>${cards(['agriculture','hunting','restaurant'],x=>`<article class="reveal"><h3>${esc(t.targetMessages[x].title)}</h3><p>${esc(t.targetMessages[x].description)}</p></article>`)}</section><section><div class="heading"><h2>${esc(t.home.latestNews)}</h2><a href="${rel(file,target(loc,'news'))}">${L.all}</a></div>${cards(news.slice(0,3),x=>`<article><time>${x.date}</time><h3><a href="${rel(file,target(loc,'news/'+x.slug))}">${esc(x.title)}</a></h3><p>${esc(x.excerpt)}</p></article>`)}</section><section class="cta"><h2>${esc(t.home.ctaTitle)}</h2>${paras(t.home.ctaDescription)}<a class="button" href="${rel(file,target(loc,'contact'))}">${esc(t.home.ctaButton)}</a></section>`;title=L.home}
 else if(page==='about'){let info=[[t.about.companyName,`${company.name}（${company.nameEn}）`],[t.about.established,company.established],[t.about.representative,company.representative],[t.about.address,company.address],[t.about.capital,company.capital]];body=`<section><h1>${L.about}</h1><h2>${esc(t.about.companyInfo)}</h2><dl class="company">${info.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></section><section><h2>${esc(t.about.business)}</h2>${cards(company.business,x=>`<article class="reveal"><p>${esc(x)}</p></article>`)}</section><section><article class="message"><h2>${esc(t.about.message)}</h2>${paras(company.message)}<p class="representative">${esc(t.about.representativeTitle)} ${esc(company.representative)}</p></article></section>`;title=L.about}
 else if(page==='news'){body=`<section><h1>${L.news}</h1>${cards(news,x=>`<article><time>${x.date}</time><p class="tag">${esc(x.category)}</p><h2><a href="${rel(file,target(loc,'news/'+x.slug))}">${esc(x.title)}</a></h2><p>${esc(x.excerpt)}</p></article>`)}</section>`;title=L.news}
 else if(page.startsWith('news/')){let x=news.find(y=>y.slug===slug);body=`<article class="detail"><a href="${rel(file,target(loc,'news'))}">← ${L.back}</a><time>${x.date}</time><p class="tag">${esc(x.category)}</p><h1>${esc(x.title)}</h1>${paras(x.body)}${(x.links||[]).map(z=>`<p><a class="button" target="_blank" rel="noopener" href="${esc(z.url)}">${esc(z.label)} ↗</a></p>`).join('')}</article>`;title=x.title}
 else if(page==='announcements'){body=`<section><h1>${L.ann}</h1>${ann.length?cards(ann,x=>`<article><time>${x.date}</time><h2>${esc(x.title)}</h2><p>${esc(x.excerpt)}</p></article>`):`<p class="empty">${esc(t.announcements.empty)}</p>`}</section>`;title=L.ann}
 else if(page==='partners'){body=`<section><h1>${L.partners}</h1><p class="lead">${esc(t.partners.description)}</p>${cards(partners,x=>`<article><p class="tag">${esc(x.category)}</p><h2>${esc(x.name)}</h2><p>${esc(x.comment)}</p><a target="_blank" rel="noopener" href="${esc(x.url)}">${esc(x.url)} ↗</a></article>`)}</section>`;title=L.partners}
 else if(page==='contact'){body=`<section><h1>${L.contact}</h1><p class="lead">${esc(t.contact.description)}</p><form action="mailto:info@best-ies.com" method="post"><label>${esc(t.contact.name)}<input name="name" required></label><label>${esc(t.contact.subject)}<input name="subject" required></label><label>${esc(t.contact.message)}<textarea name="body" rows="8" required></textarea></label><button>${esc(t.contact.submit)}</button></form></section>`;title=L.contact}
 else {body=`<section><h1>${esc(pol.title)}</h1><p class="lead">${esc(pol.description)}</p>${cards(pol.sections,x=>`<article><h2>${esc(x.title)}</h2>${paras(x.body)}</article>`)}<div class="signature"><p>${esc(pol.establishedLabel)} ${esc(pol.establishedDate)}</p><p>${esc(pol.company)}<br>${esc(pol.representative)}</p></div></section>`;title=L.security}
 let out=path.join(root,base,file);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,shell(ctx,title,body));}
for(let n=1;n<=10;n++){let base=path.join(root,'concepts',String(n).padStart(2,'0'));fs.mkdirSync(path.join(base,'assets'),{recursive:true});fs.copyFileSync(path.join(root,'assets',`hero-${String(n).padStart(2,'0')}.webp`),path.join(base,'assets','hero.webp'));fs.copyFileSync(path.join(root,'site-template.css'),path.join(base,'assets','site.css'));fs.copyFileSync(path.join(root,'site-template.js'),path.join(base,'assets','site.js'));for(const loc of locales){for(const p of ['home','about','news','announcements','partners','contact','security-policy'])build(n,loc,p);for(const x of content(loc,'news'))build(n,loc,'news/'+x.slug,x.slug)}}
console.log('Generated 300 static HTML pages.');

// Keep proposal-only pages aligned with the production site's shared chrome and
// make every local-file asset self-contained after generation.
for(let n=1;n<=10;n++){
 const base=path.join(root,'concepts',String(n).padStart(2,'0'));
 fs.copyFileSync(path.join(repo,'public/images/Logo.svg'),path.join(base,'assets/Logo.svg'));
 fs.copyFileSync(path.join(repo,'public/images/background.png'),path.join(base,'assets/scene.png'));
 fs.copyFileSync(path.join(root,'site-overrides.css'),path.join(base,'assets/site-overrides.css'));
 for(const file of fs.readdirSync(path.join(base,'site'),{recursive:true}).filter(x=>x.endsWith('.html'))){
  const full=path.join(base,'site',file);let html=fs.readFileSync(full,'utf8');
  const from=path.relative(path.dirname(path.join('site',file)),'assets').replaceAll('\\','/');
  html=html.replace(`</head>`,`<link rel="stylesheet" href="${from}/site-overrides.css"></head>`);
  // Use real image elements so local file:// previews never depend on CSS custom
  // property URL resolution. The generated pages stay fully portable.
  html=html.replace(/ style="--hero:url\('[^']+'\)"/,``);
  html=html.replace(`<section class="hero">`,`<section class="hero"><img class="hero-media" src="${from}/hero.webp" alt="">`);
  html=html.replace(`<section class="scene">`,`<section class="scene"><img class="scene-media" src="${from}/scene.png" alt="">`);
  html=html.replace(/<a class="brand"([^>]*)>best<span>IE<\/span>s<\/a>/,`<a class="brand"$1><img src="${from}/Logo.svg" alt="bestIEs"></a>`);
  html=html.replace(/<a target="_blank" rel="noopener" href="([^"]+)">https?:\/\/[^<]+ ↗<\/a>/g,(_,url)=>`<a class="button partner-link" target="_blank" rel="noopener" href="${url}">${file.startsWith('ja\\')?'公式サイトを見る':file.startsWith('zh\\')?'查看官方网站':'Visit official site'} ↗</a>`);
  fs.writeFileSync(full,html);
 }
}
